"""governed research and local paper runtime

Revision ID: 0984b8c06f2e
Revises: a14f0c9d7e62
Create Date: 2026-08-13 14:32:28.136180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0984b8c06f2e'
down_revision: Union[str, Sequence[str], None] = 'a14f0c9d7e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('issue_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('issue_code', sa.String(length=60), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=False),
    sa.Column('raw_data_hash', sa.String(length=64), nullable=False),
    sa.Column('disposition', sa.String(length=40), nullable=False),
    sa.Column('normalization_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=False),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decision_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['dataset_snapshots.id'], name=op.f('fk_data_quality_decisions_source_snapshot_id_dataset_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_decisions')),
    sa.UniqueConstraint('decision_hash', name=op.f('uq_data_quality_decisions_decision_hash')),
    sa.UniqueConstraint('source_snapshot_id', 'issue_fingerprint', name='uq_data_quality_decisions_snapshot_issue')
    )
    with op.batch_alter_table('data_quality_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_data_quality_decisions_snapshot_ticker_dates', ['source_snapshot_id', 'ticker', 'start_date', 'end_date'], unique=False)

    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('account_ref', sa.String(length=80), nullable=False),
    sa.Column('strategy_version', sa.String(length=40), nullable=False),
    sa.Column('nav', sa.Float(), nullable=False),
    sa.Column('settled_cash', sa.Float(), nullable=False),
    sa.Column('available_cash', sa.Float(), nullable=False),
    sa.Column('positions_json', sa.JSON(), nullable=False),
    sa.Column('high_water', sa.Float(), nullable=False),
    sa.Column('risk_state', sa.String(length=30), server_default='NORMAL', nullable=False),
    sa.Column('last_valuation_session', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version'], ['strategy_versions.version'], name=op.f('fk_paper_accounts_strategy_version_strategy_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_accounts')),
    sa.UniqueConstraint('environment', 'account_ref', name='uq_paper_accounts_environment_account_ref')
    )
    op.create_table('signal_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_key', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('strategy_version', sa.String(length=40), nullable=False),
    sa.Column('universe_version', sa.String(length=40), nullable=False),
    sa.Column('dataset_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('signal_session', sa.String(length=20), nullable=False),
    sa.Column('data_as_of', sa.String(length=40), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('next_rebalance_session', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('regime', sa.String(length=40), nullable=False),
    sa.Column('decision_json', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_snapshot_id'], ['dataset_snapshots.id'], name=op.f('fk_signal_decisions_dataset_snapshot_id_dataset_snapshots')),
    sa.ForeignKeyConstraint(['strategy_version'], ['strategy_versions.version'], name=op.f('fk_signal_decisions_strategy_version_strategy_versions')),
    sa.ForeignKeyConstraint(['universe_version'], ['universe_versions.version'], name=op.f('fk_signal_decisions_universe_version_universe_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_decisions')),
    sa.UniqueConstraint('decision_key', name=op.f('uq_signal_decisions_decision_key')),
    sa.UniqueConstraint('environment', 'strategy_version', 'signal_session', name='uq_signal_decisions_environment_strategy_session')
    )
    op.create_table('paper_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('strategy_version', sa.String(length=40), nullable=False),
    sa.Column('signal_decision_id', sa.Integer(), nullable=False),
    sa.Column('signal_session', sa.String(length=20), nullable=False),
    sa.Column('execution_session', sa.String(length=20), nullable=False),
    sa.Column('approval_deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('missed_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_decision_id'], ['signal_decisions.id'], name=op.f('fk_paper_cycles_signal_decision_id_signal_decisions')),
    sa.ForeignKeyConstraint(['strategy_version'], ['strategy_versions.version'], name=op.f('fk_paper_cycles_strategy_version_strategy_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_cycles')),
    sa.UniqueConstraint('environment', 'strategy_version', 'signal_session', name='uq_paper_cycles_environment_strategy_session')
    )
    op.create_table('paper_cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_key', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('order_intent_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('trade_date', sa.String(length=20), nullable=False),
    sa.Column('settlement_date', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], name=op.f('fk_paper_cash_movements_account_id_paper_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_intent_id'], ['order_intents.id'], name=op.f('fk_paper_cash_movements_order_intent_id_order_intents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_cash_movements')),
    sa.UniqueConstraint('movement_key', name=op.f('uq_paper_cash_movements_movement_key'))
    )
    with op.batch_alter_table('paper_cash_movements', schema=None) as batch_op:
        batch_op.create_index('ix_paper_cash_movements_account_settlement', ['account_id', 'settlement_date'], unique=False)

    with op.batch_alter_table('admission_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_admission_runs_strategy_version_strategy_versions'), 'strategy_versions', ['strategy_version'], ['version'], ondelete='CASCADE')

    with op.batch_alter_table('dataset_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_set_hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('execution_fills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settlement_date', sa.String(length=20), nullable=True))

    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_experiment_runs_dataset_snapshot_id_dataset_snapshots'), 'dataset_snapshots', ['dataset_snapshot_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_experiment_runs_strategy_version_strategy_versions'), 'strategy_versions', ['strategy_version'], ['version'])
        batch_op.create_foreign_key(batch_op.f('fk_experiment_runs_universe_version_universe_versions'), 'universe_versions', ['universe_version'], ['version'])

    with op.batch_alter_table('order_intents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signal_decision_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paper_cycle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_type', sa.String(length=20), server_default='LMT', nullable=False))
        batch_op.add_column(sa.Column('execution_session', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('filled_quantity', sa.Float(), server_default='0', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_order_intents_strategy_version_strategy_versions'), 'strategy_versions', ['strategy_version'], ['version'])
        batch_op.create_foreign_key(batch_op.f('fk_order_intents_signal_decision_id_signal_decisions'), 'signal_decisions', ['signal_decision_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_order_intents_paper_cycle_id_paper_cycles'), 'paper_cycles', ['paper_cycle_id'], ['id'])

    with op.batch_alter_table('parameter_trials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(length=30), server_default='final', nullable=False))
        batch_op.add_column(sa.Column('fold_key', sa.String(length=100), server_default='ALL', nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_parameter_trials_admission_label'), type_='unique')
        batch_op.create_unique_constraint('uq_parameter_trials_admission_stage_fold_label', ['admission_run_id', 'stage', 'fold_key', 'label'])

    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_cycle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reconciliations_paper_cycle_id_paper_cycles'), 'paper_cycles', ['paper_cycle_id'], ['id'])

    with op.batch_alter_table('risk_incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environment', sa.String(length=20), server_default='PAPER', nullable=False))
        batch_op.add_column(sa.Column('account_ref', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('paper_cycle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reconciliation_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_intent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recovery_authorized_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('recovery_authorized_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notification_status', sa.String(length=20), server_default='PENDING', nullable=False))
        batch_op.add_column(sa.Column('notification_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notification_attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('notification_last_error', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_risk_incidents_paper_cycle_id_paper_cycles'), 'paper_cycles', ['paper_cycle_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_risk_incidents_strategy_version_strategy_versions'), 'strategy_versions', ['strategy_version'], ['version'])
        batch_op.create_foreign_key(batch_op.f('fk_risk_incidents_order_intent_id_order_intents'), 'order_intents', ['order_intent_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_risk_incidents_reconciliation_id_reconciliations'), 'reconciliations', ['reconciliation_id'], ['id'])

    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_sim_start', sa.DateTime(), nullable=True))
        batch_op.alter_column('dataset_snapshot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_strategy_versions_dataset_snapshot_id_dataset_snapshots'), 'dataset_snapshots', ['dataset_snapshot_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_strategy_versions_universe_version_universe_versions'), 'universe_versions', ['universe_version'], ['version'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_strategy_versions_universe_version_universe_versions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_strategy_versions_dataset_snapshot_id_dataset_snapshots'), type_='foreignkey')
        batch_op.alter_column('dataset_snapshot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('local_sim_start')

    with op.batch_alter_table('risk_incidents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_risk_incidents_reconciliation_id_reconciliations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_risk_incidents_order_intent_id_order_intents'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_risk_incidents_strategy_version_strategy_versions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_risk_incidents_paper_cycle_id_paper_cycles'), type_='foreignkey')
        batch_op.drop_column('notification_last_error')
        batch_op.drop_column('notification_attempts')
        batch_op.drop_column('notification_request_id')
        batch_op.drop_column('notification_status')
        batch_op.drop_column('recovery_authorized_at')
        batch_op.drop_column('recovery_authorized_by')
        batch_op.drop_column('order_intent_id')
        batch_op.drop_column('reconciliation_id')
        batch_op.drop_column('paper_cycle_id')
        batch_op.drop_column('account_ref')
        batch_op.drop_column('environment')

    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reconciliations_paper_cycle_id_paper_cycles'), type_='foreignkey')
        batch_op.drop_column('paper_cycle_id')

    with op.batch_alter_table('parameter_trials', schema=None) as batch_op:
        batch_op.drop_constraint('uq_parameter_trials_admission_stage_fold_label', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_parameter_trials_admission_label'), ['admission_run_id', 'label'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('fold_key')
        batch_op.drop_column('stage')

    with op.batch_alter_table('order_intents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_intents_paper_cycle_id_paper_cycles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_order_intents_signal_decision_id_signal_decisions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_order_intents_strategy_version_strategy_versions'), type_='foreignkey')
        batch_op.drop_column('filled_quantity')
        batch_op.drop_column('execution_session')
        batch_op.drop_column('order_type')
        batch_op.drop_column('paper_cycle_id')
        batch_op.drop_column('signal_decision_id')

    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_experiment_runs_universe_version_universe_versions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_experiment_runs_strategy_version_strategy_versions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_experiment_runs_dataset_snapshot_id_dataset_snapshots'), type_='foreignkey')

    with op.batch_alter_table('execution_fills', schema=None) as batch_op:
        batch_op.drop_column('settlement_date')

    with op.batch_alter_table('dataset_snapshots', schema=None) as batch_op:
        batch_op.drop_column('decision_set_hash')

    with op.batch_alter_table('admission_runs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_admission_runs_strategy_version_strategy_versions'), type_='foreignkey')
        batch_op.drop_column('error_message')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('paper_cash_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_paper_cash_movements_account_settlement')

    op.drop_table('paper_cash_movements')
    op.drop_table('paper_cycles')
    op.drop_table('signal_decisions')
    op.drop_table('paper_accounts')
    with op.batch_alter_table('data_quality_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_data_quality_decisions_snapshot_ticker_dates')

    op.drop_table('data_quality_decisions')
    # ### end Alembic commands ###
