"""initial schema

Revision ID: e3d6c6759be2
Revises: 
Create Date: 2026-06-24 15:34:20.573674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d6c6759be2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('scenario_name', sa.String(length=200), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('benchmark', sa.String(length=20), nullable=True),
    sa.Column('rebalance_frequency', sa.String(length=4), nullable=True),
    sa.Column('top_n', sa.Integer(), nullable=True),
    sa.Column('min_momentum_threshold', sa.Float(), nullable=True),
    sa.Column('target_annual_vol', sa.Float(), nullable=True),
    sa.Column('max_asset_weight', sa.Float(), nullable=True),
    sa.Column('risk_off_cash_weight', sa.Float(), nullable=True),
    sa.Column('vix_risk_off_threshold', sa.Float(), nullable=True),
    sa.Column('vix_high_threshold', sa.Float(), nullable=True),
    sa.Column('trading_cost_bps', sa.Float(), nullable=True),
    sa.Column('start_equity', sa.Float(), nullable=True),
    sa.Column('end_equity', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('annual_vol', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('sortino', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('avg_turnover', sa.Float(), nullable=True),
    sa.Column('latest_signal_date', sa.String(length=20), nullable=True),
    sa.Column('latest_regime', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='complete', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_runs'))
    )
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.create_index('ix_experiment_runs_config_hash', ['config_hash'], unique=False)
        batch_op.create_index('ix_experiment_runs_scenario_name', ['scenario_name'], unique=False)

    op.create_table('market_data',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('auto_adjusted', sa.Integer(), server_default='1', nullable=False),
    sa.Column('source', sa.String(length=40), server_default='yfinance', nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date', name=op.f('pk_market_data'))
    )
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.create_index('ix_market_data_ticker_date', ['ticker', 'date'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('weight_change', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('est_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], name=op.f('fk_orders_run_id_experiment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_run_id', ['run_id'], unique=False)

    op.create_table('portfolio_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=40), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('est_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], name=op.f('fk_portfolio_daily_run_id_experiment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_daily')),
    sa.UniqueConstraint('run_id', 'date', name='uq_portfolio_daily_run_id_date')
    )
    with op.batch_alter_table('portfolio_daily', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_daily_run_id_date', ['run_id', 'date'], unique=False)

    op.create_table('portfolio_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], name=op.f('fk_portfolio_weights_run_id_experiment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_weights')),
    sa.UniqueConstraint('run_id', 'date', 'ticker', name='uq_portfolio_weights_run_id_date_ticker')
    )
    with op.batch_alter_table('portfolio_weights', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_weights_run_id_date', ['run_id', 'date'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('signal_date', sa.String(length=20), nullable=False),
    sa.Column('regime', sa.String(length=40), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], name=op.f('fk_signals_run_id_experiment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signals_run_id', ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index('ix_signals_run_id')

    op.drop_table('signals')
    with op.batch_alter_table('portfolio_weights', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_weights_run_id_date')

    op.drop_table('portfolio_weights')
    with op.batch_alter_table('portfolio_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_daily_run_id_date')

    op.drop_table('portfolio_daily')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_run_id')

    op.drop_table('orders')
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_index('ix_market_data_ticker_date')

    op.drop_table('market_data')
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_experiment_runs_scenario_name')
        batch_op.drop_index('ix_experiment_runs_config_hash')

    op.drop_table('experiment_runs')
    # ### end Alembic commands ###
