from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
import hashlib
import math
from pathlib import Path
from typing import Iterable, Mapping


EXPECTED_METHODOLOGY = "expanding_walk_forward_with_untouched_holdout"
FINGERPRINTED_SOURCE_DIRECTORIES = (
    "backtest",
    "config",
    "data",
    "research",
    "risk",
    "strategy",
    "utils",
)
OPTIMIZER_SOURCE = Path("scripts/optimize_mirrored_portfolio.py")


def calculate_optimizer_source_fingerprint(project_root: Path) -> str:
    """Fingerprint the exact research sources used by the mirror optimizer."""
    files = [project_root / OPTIMIZER_SOURCE]
    for directory in FINGERPRINTED_SOURCE_DIRECTORIES:
        files.extend((project_root / directory).rglob("*.py"))
    digest = hashlib.sha256()
    for path in sorted(set(files)):
        digest.update(str(path.relative_to(project_root)).encode("utf-8"))
        digest.update(path.read_bytes())
    return digest.hexdigest()


def optimization_result_error(
    result: object,
    current_snapshot_id: int,
    *,
    expected_source_fingerprint: str | None = None,
    snapshot_captured_at: object | None = None,
    now: datetime | None = None,
    maximum_age: timedelta = timedelta(days=7),
) -> str:
    """Return why a mirror optimization result must not be displayed as current."""
    if result == {}:
        return ""
    if not isinstance(result, Mapping):
        return "Optimization result must be a JSON object and is blocked."
    if (
        result.get("schema_version") != 2
        or result.get("methodology") != EXPECTED_METHODOLOGY
    ):
        return (
            "Legacy single-split optimization result is blocked. Rerun the "
            "strict walk-forward optimizer."
        )
    if result.get("mirror_snapshot_id") != current_snapshot_id:
        return (
            "Optimization result belongs to a different mirror snapshot and "
            "is blocked until the optimizer is rerun."
        )

    required_fields = {
        "generated_at",
        "source_fingerprint",
        "best",
        "admission",
        "admitted",
        "position_changes_authorized",
        "latest_signal_date",
        "latest_weights",
    }
    missing = sorted(required_fields - set(result))
    if missing:
        return (
            "Optimization result is incomplete and is blocked. Missing: "
            + ", ".join(missing)
        )

    fingerprint = result.get("source_fingerprint")
    if (
        not isinstance(fingerprint, str)
        or len(fingerprint) != 64
        or any(character not in "0123456789abcdefABCDEF" for character in fingerprint)
    ):
        return "Optimization source fingerprint is invalid and the result is blocked."
    if (
        expected_source_fingerprint is not None
        and fingerprint.lower() != expected_source_fingerprint.lower()
    ):
        return (
            "Optimization result was generated by different source code and "
            "is blocked until the optimizer is rerun."
        )

    generated_at = _parse_datetime(result.get("generated_at"))
    if generated_at is None or generated_at.tzinfo is None:
        return (
            "Optimization generation time is invalid or timezone-naive and "
            "the result is blocked."
        )
    generated_at = generated_at.astimezone(timezone.utc)
    captured_at = _parse_datetime(snapshot_captured_at, assume_utc=True)
    if snapshot_captured_at is not None and captured_at is None:
        return "Mirror snapshot capture time is invalid and the result is blocked."
    if captured_at is not None and generated_at < captured_at:
        return (
            "Optimization result predates the current mirror snapshot and is "
            "blocked until the optimizer is rerun."
        )
    current_time = now or datetime.now(timezone.utc)
    if current_time.tzinfo is None:
        current_time = current_time.replace(tzinfo=timezone.utc)
    current_time = current_time.astimezone(timezone.utc)
    if generated_at > current_time + timedelta(minutes=5):
        return "Optimization generation time is in the future and is blocked."
    if current_time - generated_at > maximum_age:
        return (
            "Optimization result is older than the allowed freshness window "
            "and is blocked until the optimizer is rerun."
        )

    try:
        date.fromisoformat(str(result.get("latest_signal_date")))
    except ValueError:
        return "Optimization signal date is invalid and the result is blocked."

    best = result.get("best")
    required_metrics = {
        "test_cagr",
        "test_sharpe",
        "test_max_drawdown",
        "test_annual_turnover",
    }
    if not isinstance(best, Mapping) or not required_metrics.issubset(best):
        return "Optimization holdout metrics are incomplete and the result is blocked."
    if any(not _finite_number(best[name]) for name in required_metrics):
        return "Optimization holdout metrics contain invalid values and are blocked."
    if float(best["test_annual_turnover"]) < 0.0:
        return "Optimization turnover cannot be negative and the result is blocked."

    weights = result.get("latest_weights")
    if not isinstance(weights, Mapping) or not weights:
        return "Optimization target weights are missing and the result is blocked."
    if any(
        not isinstance(symbol, str)
        or not symbol.strip()
        or not _finite_number(weight)
        or float(weight) < 0.0
        or float(weight) > 1.0
        for symbol, weight in weights.items()
    ):
        return "Optimization target weights are invalid and the result is blocked."
    if not math.isclose(
        sum(float(weight) for weight in weights.values()),
        1.0,
        rel_tol=0.0,
        abs_tol=1e-6,
    ):
        return "Optimization target weights do not sum to 1 and are blocked."

    admission = result.get("admission")
    if not isinstance(admission, Mapping):
        return "Optimization admission audit is missing and the result is blocked."
    gates = admission.get("gates")
    if (
        not isinstance(gates, Mapping)
        or not gates
        or any(not isinstance(value, bool) for value in gates.values())
    ):
        return "Optimization admission gates are invalid and the result is blocked."
    admitted = result.get("admitted")
    position_authorized = result.get("position_changes_authorized")
    if not isinstance(admitted, bool) or not isinstance(position_authorized, bool):
        return "Optimization authorization flags are invalid and the result is blocked."
    if admission.get("selection_uses_holdout") is not False:
        return "Optimization holdout isolation is invalid and the result is blocked."
    if admission.get("admitted") is not admitted or admission.get(
        "position_changes_authorized"
    ) is not position_authorized:
        return "Optimization admission flags are inconsistent and are blocked."
    if admitted is not all(gates.values()):
        return "Optimization gate decision is inconsistent and the result is blocked."
    if position_authorized and not admitted:
        return "Unauthorized optimization position changes are blocked."
    return ""


def normalize_cost_basis_weights(
    values: Iterable[object],
) -> tuple[list[float], float, bool]:
    """Return safe normalized weights and whether the total cost basis is valid."""
    raw_values = list(values)
    converted = []
    for value in raw_values:
        if not _finite_number(value) or float(value) < 0.0:
            return [0.0] * len(raw_values), math.nan, False
        converted.append(float(value))
    total = math.fsum(converted)
    if total <= 0.0 or not math.isfinite(total):
        return [0.0] * len(converted), total, False
    return [value / total for value in converted], total, True


def _finite_number(value: object) -> bool:
    return (
        isinstance(value, (int, float))
        and not isinstance(value, bool)
        and math.isfinite(float(value))
    )


def _parse_datetime(value: object, *, assume_utc: bool = False) -> datetime | None:
    if value is None:
        return None
    if hasattr(value, "to_pydatetime"):
        value = value.to_pydatetime()
    if isinstance(value, datetime):
        parsed = value
    elif isinstance(value, str):
        try:
            parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError:
            return None
    else:
        return None
    if parsed.tzinfo is None and assume_utc:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed
